<?php

/**
 * @file
 * Contains pledge_import.module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function pledge_import_migration_plugins_alter(&$definitions) {
  $migrations = [
    'pledge_statuses',
    'pledge_milestone_statuses',
  ];

  foreach ($migrations as $migration) {
    $definitions[$migration]['source']['path'] = drupal_get_path('module', 'pledge_import') . $definitions[$migration]['source']['path'];
  }
}
