<?php

/**
 * @file
 * Contains pledge_core.module.
 */

use \Drupal\Core\Breadcrumb\Breadcrumb;
use \Drupal\Core\Routing\RouteMatchInterface;

function pledge_core_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
//  var_dump($breadcrumb);
//  var_dump($route_match);
//  var_dump($context);
//  exit('pledge_theme_system_breadcrumb_alter');
}

/**
 * Implements hook_preprocess_field().
 *
 * Removes title field from node display.
 */
function pledge_core_preprocess_field(&$variables) {

//  if ($variables['field_name'] == 'title') {
//    if ($node = \Drupal::request()->attributes->get('node')) {
//      foreach ($variables['items'] as $index => $item) {
//        $variables['items'][$index]['content']['#context']['value'] = '';
//      }
//    }
//  }
}